/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx_gpio_driver.h"

int main(void)
{
    GPIO_Handle_t gpioLed = {0};
    
    gpioLed.pGPIOx = GPIOA;

    gpioLed.GPIO_PinConfig.pinNumber = GPIO_PIN_6;
    gpioLed.GPIO_PinConfig.mode = GPIO_MODE_OUTPUT;
    gpioLed.GPIO_PinConfig.speed = GPIO_SPEED_FAST;
    gpioLed.GPIO_PinConfig.opType = GPIO_OP_TYPE_PP;
    gpioLed.GPIO_PinConfig.pupd = GPIO_NO_PUPD;

    GPIO_PeriClockControl(GPIOA, ENABLE);
    GPIO_Init(&gpioLed);
    while(1)
    {
        GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_6);
        for(volatile uint32_t i = 0; i < 500000; i++);
    }
    return 0;
}
