/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx_gpio_driver.h"

int main(void)
{
    GPIO_Handle_t gpioLed = {0};
    
    gpioLed.pGPIOx = GPIOA;
    gpioLed.GPIO_PinConfig.pinNumber = GPIO_PIN_6;
    gpioLed.GPIO_PinConfig.mode = GPIO_MODE_OUTPUT;
    gpioLed.GPIO_PinConfig.speed = GPIO_SPEED_FAST;
    gpioLed.GPIO_PinConfig.opType = GPIO_OP_TYPE_OD;
    gpioLed.GPIO_PinConfig.pupd = GPIO_NO_PUPD;

    //k0 button to PA0
    GPIO_Handle_t gpioButton = {0};
    gpioButton.pGPIOx = GPIOA;
    gpioButton.GPIO_PinConfig.pinNumber = GPIO_PIN_0;
    gpioButton.GPIO_PinConfig.mode = GPIO_MODE_IT_FT; // Interrupt on falling edge
    gpioButton.GPIO_PinConfig.speed = GPIO_SPEED_FAST;
    gpioButton.GPIO_PinConfig.pupd = GPIO_NO_PUPD;

    GPIO_PeriClockControl(GPIOA, ENABLE);
    GPIO_Init(&gpioLed);
    GPIO_Init(&gpioButton);


    // Enable EXTI0 interrupt in NVIC
    GPIO_IRQConfig(IRQ_NO_EXTI0, ENABLE);
    GPIO_IRQPriorityConfig(IRQ_NO_EXTI0, 15);

    while(1)
    {
        if(GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_0) == 1)
        {
        	for(volatile uint32_t i = 0; i < 500000; i++);
            GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_6);
            while(GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_0) == 1);
            for(volatile uint32_t i = 0; i < 500000; i++);
        
        }

    }
    return 0;
}
void EXTI0_IRQHandler()
{
    GPIO_IRQHandling(0);
    GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_6);
}